import RoleChecker from "@/components/RoleChecker";
import { UserRole } from "@/types";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <RoleChecker requiredRole={UserRole.ADMIN}>{children} </RoleChecker>
    </>
  );
}
