import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./header";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "h-full flex flex-col bg-[radial-gradient(ellipse_at_left,_var(--tw-gradient-stops))] from-purple-300 to-teal-300"
        )}
      >
        <Providers>
          <Header />
          <div className="flex align-middle justify-center flex-grow">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
